/** Phase 8 design-system primitives — barrel export so a future page
 *  migration can `import { Button, TextField, Card } from
 *  '@/features/shared/ui'` instead of one import per file. */
export { Button } from './Button'
export type { ButtonProps } from './Button'
export { LinkButton } from './LinkButton'
export type { LinkButtonProps } from './LinkButton'
export { buttonClass } from './buttonClasses'
export type { ButtonVariant, ButtonSize } from './buttonClasses'

export { TextField } from './TextField'
export type { TextFieldProps } from './TextField'
export { SelectField } from './SelectField'
export type { SelectFieldProps } from './SelectField'
export { TextareaField } from './TextareaField'
export type { TextareaFieldProps } from './TextareaField'
export { DateField } from './DateField'
export type { DateFieldProps } from './DateField'
export { SearchField } from './SearchField'
export type { SearchFieldProps } from './SearchField'
export { FieldShell } from './FieldShell'
export { inputClass } from './inputClasses'

export { Card, CardHeader, CardSection } from './Card'
export { DetailRow } from './DetailRow'
export { StatusBadge } from './StatusBadge'
export type { StatusBadgeProps } from './StatusBadge'
export { Dialog } from './Dialog'
export { ToastProvider } from './Toast'
export { useToast } from './toastContext'
export type { ToastTone } from './toastContext'
export { PageContainer } from './PageContainer'
export { SectionHeader } from './SectionHeader'
export { LoadingState } from './LoadingState'
export { DataTable } from './DataTable'
export type { DataTableColumn } from './DataTable'
